/**
 * Common Passwords Denylist
 * 
 * Top ~150 most common and leaked passwords based on:
 * - NCSC/HIBP most common passwords
 * - SplashData worst passwords lists
 * - Common keyboard patterns and sequences
 * 
 * This list is checked case-insensitively with spaces removed.
 */
export const COMMON_PASSWORDS = new Set<string>([
  // Top 50 most common
  '123456',
  'password',
  '123456789',
  '12345678',
  '12345',
  '111111',
  '1234567',
  'sunshine',
  'qwerty',
  'iloveyou',
  'princess',
  'admin',
  'welcome',
  '666666',
  'abc123',
  'football',
  '123123',
  'monkey',
  '654321',
  '!@#$%^&*',
  'charlie',
  'aa123456',
  'donald',
  'password1',
  'qwerty123',
  
  // Common with numbers/symbols
  '1234567890',
  '0',
  '1234',
  'password123',
  '1q2w3e4r',
  '1qaz2wsx',
  'passw0rd',
  'qwertyuiop',
  '123321',
  '000000',
  
  // Common words
  'dragon',
  'master',
  'michael',
  'superman',
  'batman',
  'trustno1',
  'jordan',
  'jennifer',
  'hunter',
  'buster',
  'soccer',
  'harley',
  'ranger',
  'shadow',
  'ashley',
  'sunshine',
  'whatever',
  'daniel',
  'andrew',
  'joshua',
  'thomas',
  'bailey',
  'nicole',
  'michelle',
  'jessica',
  'matthew',
  'robert',
  'william',
  
  // Keyboard patterns
  'qwertyuiop',
  'asdfghjkl',
  'zxcvbnm',
  'qweasdzxc',
  'asdfgh',
  'zxcvbn',
  '1qaz2wsx',
  'qazwsx',
  'qweasd',
  'zaq12wsx',
  'xsw23edc',
  
  // Tech/gaming
  'login',
  'welcome',
  'passw0rd',
  'letmein',
  'mypass',
  'mypassword',
  'pass',
  'default',
  'guest',
  'test',
  'temp',
  'changeme',
  'computer',
  'internet',
  'starwars',
  'pokemon',
  'minecraft',
  'roblox',
  'fortnite',
  
  // With year suffixes (common pattern)
  'password2023',
  'password2024',
  'password2025',
  'welcome2023',
  'welcome2024',
  'welcome2025',
  'abc1234',
  'pass1234',
  'admin123',
  'root123',
  'user123',
  
  // Simple repeated patterns
  'aaaa',
  'aaaaaa',
  'aaaaaaaa',
  'bbbbbbbb',
  '11111111',
  '22222222',
  '00000000',
  'abcabc',
  '123123123',
  
  // Common phrases
  'iloveyou',
  'iloveu',
  'loveyou',
  'fuckyou',
  'fuckoff',
  'baseball',
  'basketball',
  
  // Simple sequences (these are also caught by pattern detection, but explicit is safer)
  'abcdef',
  'abcdefg',
  'abcdefgh',
  'abcdefghi',
  '123456789',
  '1234567890',
  '987654321',
  'qwerty',
  'qwertyui',
  'asdfghjk',
  
  // Common with special chars
  'password!',
  'password@',
  'password#',
  'password$',
  'password1!',
  'qwerty!',
  'qwerty1',
  'qwerty12',
  'abc123!',
  'welcome!',
  'admin!',
  
  // International common
  'senha',
  'senha123',
  'contrasena',
  'mot2passe',
  'passwort',
]);
