// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { memoryStorage } from './memoryStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * SECURITY HARDENING: In-Memory Session Storage
 * 
 * This configuration prevents auth token exposure to XSS attacks by:
 * 1. Using in-memory storage instead of localStorage (not accessible to injected scripts after page load)
 * 2. Disabling session persistence (tokens don't survive page reloads)
 * 3. Disabling auto token refresh (minimizes token lifetime exposure)
 * 
 * TRADE-OFF: Users will be logged out on page refresh and must re-authenticate.
 * This is a conscious security decision to eliminate localStorage as an attack surface.
 * 
 * For production apps requiring session persistence, implement a Backend-for-Frontend (BFF)
 * pattern with HttpOnly, Secure, SameSite cookies instead.
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use in-memory storage (browser only) to prevent XSS token theft
    // SSR-safe: only use memoryStorage when window is available
    storage: typeof window !== 'undefined' ? memoryStorage : undefined,
    
    // SECURITY: Disable session persistence - tokens are not written to localStorage/sessionStorage
    persistSession: false,
    
    // SECURITY: Disable auto token refresh - minimizes window for token abuse
    autoRefreshToken: false,
  }
});